const GET_POKEMONES = "GET_POKEMONES";
const SEARCH_POKEMONES = "SEARCH_POKEMONES";
const SORT_POKEMONES_ALF = "SORT_POKEMONES_ALF";
const SORT_POKEMONES_ATK = "SORT_POKEMONES_ATK";
const ADD_POKEMONES = "ADD_POKEMONES";
const FILTER_POKEMONES_API = "FILTER_POKEMONES_API";
const ADD_TYPES = "ADD_TYPES";
const DETAIL_POKEMONES = "DETAIL_POKEMONES";
const FILTER_POKEMONES_DB = "FILTER_POKEMONES_DB";
const FILTER_POKEMONES_TYPE = "FILTER_POKEMONES_TYPE";

module.exports = {
  FILTER_POKEMONES_API,
  FILTER_POKEMONES_TYPE,
  FILTER_POKEMONES_DB,
  GET_POKEMONES,
  SEARCH_POKEMONES,
  SORT_POKEMONES_ALF,
  SORT_POKEMONES_ATK,
  ADD_POKEMONES,
  ADD_TYPES,
  DETAIL_POKEMONES,
};
